server:
  port: 8080
spring:
  datasource:
    username: root
    password: skillbox
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.jdbc.batch_size: 200
    hibernate.ddl-auto: create
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
connect-settings:
  sleepTime: 50
  userAgent: "Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
  referrer: "http://www.google.com"
  maxPagesCount: 50