version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: search_engine
      POSTGRES_USER: search_engine
      POSTGRES_PASSWORD: search_engine